//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyWebServer.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class Emails
    {
        public int Id { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd.MM.yyyy}")]
        [Display(Name = "Время отправки")]
        public System.DateTime EmailTime { get; set; }
        [Display(Name = "Адресат")]
        public string EmailTo { get; set; }
        [Display(Name = "Отправитель")]
        public string EmailFrom { get; set; }
        [Display(Name = "Тема")]
        public string EmailTopic { get; set; }
        [Display(Name = "Сообщение")]
        public string EmailText { get; set; }
    }
}
